name: Pages

on:
  push:
    branches:
      - main # default branch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '25'
      - run: java --version
      - name: Run
        run: java -Dfile.encoding=UTF-8 -Djava.library.path=. -cp Rukkit-0.9.4-dev-240811.jar:libs/* cn.rukkit.RukkitLauncher --nogui --no-console-input &
      
